version: '3'
services:
  pg:
    image: 'bitnami/postgresql'
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=biblioteca_test
  redis:
    image: 'redis:alpine'
    ports:
      - 6379:6379
